import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import Recetas from '../../components/client/cardRecetas';
import Head from 'next/head';
import APIConsultas from '../../services/consultas';
import Loading from '../../components/utils/loading';

const RecetaDetails = ({ id }) => {
  const title = 'Receta [id] | Lacteos Premium S.A';
  const router = useRouter();
  const [receta, setReceta] = useState('');
  const [relacionados, setRelacionados] = useState();

  const fetchData = async (index) => {
    APIConsultas.producto.GET_XID(id, true).then((prop) => {
      setReceta(prop);
      console.log(receta);
      APIConsultas.producto.GET_SHOP('recetas', true).then((relaciones) => {
        setRelacionados(relaciones);
      });
    });
  };
  useEffect(() => {
    fetchData(0);
  }, []);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof receta === 'object' ? (
        <div className="md:pt-[100px] pt-[70px] md:px-[8rem] px-10 space-y-16">
          <div className="flex justify-between gap-16">
            <div className="w-[70%]">
              <img src="/media/recetas2.png" alt="receta" className="w-full" />
            </div>
            <div className="bg-[#FAFAFA] w-[30%] rounded-[30px] p-8 text-primary-500 space-y-4">
              <h1 className="brother-700 text-xl">{receta.modelo}</h1>
              <span className="text-xs ">30 noviembre, 2020</span>
              <ul className="text-base">
                <li className="brother-700">Ingredienes:</li>
                <li>Tapa para Tarta Chica 1 u.</li>
                <li>Queso Azul 100 Gr.</li>
                <li>Queso Mozzarella 170 Gr.</li>
                <li>Crema de Leche 100 Gr.</li>
                <li>Cebolla 2 u.</li>
                <li>Manteca 30 Gr.</li>
                <li>Azúcar 50 Gr.</li>
                <li>Sal 1 Cdita.</li>
                <li>Pimienta c/n.</li>
              </ul>
            </div>
          </div>
          <div>
            <div className="w-full text-center">
              <h2 className="text-[30px] brother-800">
                El paso a paso, en el siguiente video
              </h2>
            </div>
            <div className="mt-8">
              <iframe
                className="w-full rounded-[30px]"
                height="450"
                src="https://www.youtube.com/embed/CqOGSIUAJnM"
                title="YouTube video player"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              ></iframe>
            </div>
          </div>
          <div className="pb-8">
            <div className="w-full text-center">
              <h2 className="text-[30px] brother-800">Otras recetas</h2>
            </div>
            <div className="flex gap-8  my-6 md:overflow-auto overflow-x-scroll py-1">
              {relacionados?.map((q, i) => (
                <Recetas key={i} data={q}></Recetas>
              ))}
            </div>
            <div className="flex justify-center">
              <button
                onClick={() => router.push('/recetas')}
                className="text-white md:text-[20px] text-[18px]  bg-primary-500 hover:bg-primary-600 brother-500  border-2 border-primary-500  rounded-[30px] px-4 py-1 "
              >
                Ver todas las recetas
              </button>
            </div>
          </div>
        </div>
      ) : (
        <Loading></Loading>
      )}
    </>
  );
};

export async function getServerSideProps(context) {
  const id = context.query.id;

  return {
    props: {
      id: id
    }
  };
}

export default RecetaDetails;
