import React, { useEffect, useState } from 'react';
import Recetas from '../../components/client/cardRecetas';
import Head from 'next/head';
import { useSelector } from 'react-redux';
const RecetasPage = () => {
  const title = 'Recetas | Lacteos Premium S.A';
  const state = useSelector((s) => s);
  const [recetas, setRecetas] = useState([]);

  useEffect(() => {
    setRecetas(state.recetas);
  }, [state]);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:pt-[100px] pt-[70px] md:px-[8rem] px-10">
        <div className="w-full text-center">
          <h2 className="md:text-[50px] text-[30px] brother-800">Recetas</h2>
        </div>
        <div className="grid grid-cols-4 gap-16 my-12">
          {recetas?.map((e, i) => (
            <Recetas data={e}></Recetas>
          ))}
        </div>
      </div>
    </>
  );
};

export default RecetasPage;
