import { useRouter } from 'next/router';
import React from 'react';
import NoticiasCard from '../../../components/client/swiperNoticiasCard';
import Head from 'next/head';

const Noticia = () => {
  const title = 'Novedad [id] | Lacteos Premium S.A';

  const router = useRouter();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:pt-[100px] pt-[70px] md:px-[8rem] px-10 space-y-14">
        <div className="flex gap-8 items-start">
          <div className="flex flex-col items-center justify-center w-[70%]">
            <div className="w-full max-h-[400px] overflow-hidden rounded-[30px]">
              <img
                src="/media/home2.png"
                alt="foto"
                className="w-full object-cover"
              />
            </div>
            <div className="flex flex-col gap-4 mt-2">
              <h2 className="text-[20px] brother-500 text-primary-500">
                Lácteos Premium participó del 3° Concurso de Quesos y 2°
                Concurso de Dulce de Leche y Manteca
              </h2>
              <span className="text-primary-500 text-xs">
                14 noviembre, 2022
              </span>
              <div className="text-sm space-y-6">
                <div>
                  <p>
                    El certamen fue organizado por el Ministerio de Agricultura
                    y Ganadería, la Asociación de Pequeños y Medianos
                    Empresarios Lácteos (Apymel) y la Escuela Superior de
                    Lechería de Villa María (ESIL).
                  </p>
                  <p>
                    Participaron 33 pequeñas y medianas empresas cordobesas,
                    gran parte de las cuales son empresas familiares que,
                    gracias al trabajo constante y la incorporación de
                    tecnología logran productos de calidad.
                  </p>
                  <p>
                    Pusimos en valor a la cadena láctea, que es tan importante
                    para nuestra provincia. Es un reconocimiento a las empresas
                    y trabajadores, a la producción y a lo que genera el
                    interior productivo”, afirmó el ministro de Agricultura y
                    Ganadería, Sergio Busso.
                  </p>
                </div>
                <div>
                  <p>Agradecemos los siguientes premios:</p>
                  <ul className="list-disc pl-6">
                    <li>
                      Primer Premio en la categoría quesos blandos: Queso
                      MonPrem
                    </li>
                    <li>
                      Primer Premio en la categoría de quesos semiduros con
                      ojos: Queso Gruyerito
                    </li>
                    <li>
                      Tercer Premio en la categoría de quesos saborizados y
                      especiados: Queso Marbled
                    </li>
                  </ul>
                </div>
                <div>
                  <p>
                    Es un orgullo para nuestra empresa recibir estos
                    reconocimientos. Agradecemos a cada uno de los que forman
                    parte de Lácteos Premium, desde nuestro equipo de trabajo
                    hasta asesores y productores, ya que son un eslabón muy
                    importante en nuestra cadena productiva y sin ellos no sería
                    posible.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="w-[30%] flex flex-col gap-4 px-4">
            {[1, 2, 3, 4].map((e, i) => (
              <img
                src="/media/home2.png"
                alt="foto"
                className="object-cover rounded-[30px] h-[200px] w-full"
              />
            ))}
          </div>
        </div>
        <div className="pb-16">
          <div className="w-full text-center">
            <h2 className="text-[30px] brother-800">Otras noticias</h2>
          </div>
          <div>
            <NoticiasCard></NoticiasCard>
          </div>
          <div className="flex justify-center">
            <button
              onClick={() => router.push('/novedades')}
              className="text-white md:text-[20px] text-[18px]  bg-primary-500 hover:bg-primary-600 brother-500  border-2 border-primary-500 hover:border-primary-600  rounded-[30px] px-4 py-1 "
            >
              Ver todas las novedades
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Noticia;
