import React from 'react';
import Head from 'next/head';

const Contacto = () => {
  const title = 'Contacto | Lacteos Premium S.A';

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:pt-[100px] pt-[70px] md:px-[8rem] px-10">
        <div className="w-full text-center">
          <h2 className="md:text-[50px] text-[30px] brother-800">Contacto</h2>
        </div>
        <div className="flex gap-8 text-primary-500 my-12">
          <div className="bg-[#FAFAFA] w-[50%] p-8 rounded-[30px]">
            <form className="grid grid-cols-2 gap-4 gap-y-6">
              <label className="col-span-1 flex flex-col text-sm text-primary-500">
                Nombre
                <input
                  type="text"
                  className="border-[2px] border-primary-600 rounded-[30px] py-1 px-2 "
                />
              </label>
              <label className="col-span-1 flex flex-col text-sm text-primary-500">
                Empresa
                <input
                  type="text"
                  className="border-[2px] border-primary-600 rounded-[30px] py-1 px-2"
                />
              </label>
              <label className="col-span-1 flex flex-col text-sm text-primary-500">
                Teléfono
                <input
                  type="text"
                  className="border-[2px] border-primary-600 rounded-[30px] py-1 px-2"
                />
              </label>
              <label className="col-span-1 flex flex-col text-sm text-primary-500">
                Correo electrónico
                <input
                  type="text"
                  className="border-[2px] border-primary-600 rounded-[30px] py-1 px-2"
                />
              </label>
              <label className="col-span-2 flex flex-col text-sm text-primary-500">
                Adjuntar CV
                <textarea
                  type="text"
                  className="border-[2px] border-primary-600 rounded-[30px] py-1 px-5 h-[100px]"
                />
              </label>
              <label className="col-span-2 flex flex-col text-sm text-primary-500">
                Comentario o mensaje
                <textarea
                  type="text"
                  className="border-[2px] border-primary-600 rounded-[30px] py-1 px-5 h-[100px]"
                />
              </label>
              <div className="col-span-2 flex justify-end">
                <input
                  type="submit"
                  value="Enviar"
                  className="bg-primary-600 text-white px-4 py-1 rounded-[30px] p-1 text-xl"
                />
              </div>
            </form>
          </div>
          <div className="bg-[#FAFAFA] w-[50%] p-8 rounded-[30px] flex flex-col justify-between px-16">
            <div className="flex justify-center">
              <img src="/media/logoVerde.png" alt="logo" className="w-[60%]" />
            </div>
            <div className="text-center">
              <span className="brother-500">Administración</span>
              <ul>
                <li className="text-sm">
                  Camino a la Herradura 900 mts del cruce de ruta N°2 y N°4,
                  Villa Nueva, Córdoba, Argentina
                </li>
                <li className="text-sm">Teléfono: (0353) 448323/24</li>
              </ul>
            </div>
            <div className="text-center">
              <span className="brother-500">Ventas</span>
              <ul>
                <li className="text-sm">ventas@lacteospremium.com </li>
                <li className="text-sm">3535649871</li>
              </ul>
            </div>
            <div className="text-center">
              <span className="brother-500">RRHH</span>
              <ul>
                <li className="text-sm">rrhh@lacteospremium.com</li>
              </ul>
            </div>
            <div className="text-center">
              <span className="brother-500">Administración</span>
              <ul>
                <li className="text-sm">administracion@lacteospremium.com</li>
                <li className="text-sm">3534120542</li>
              </ul>
            </div>
            <div className="text-center">
              <span className="brother-500">Horario</span>
              <ul>
                <li className="text-sm">Lunes a viernes de 8:00 a 17:30 hs.</li>
                <li className="text-sm">Sábado: 8:00 a 12:00 hs.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Contacto;
