import Head from 'next/head';
import React from 'react';
import Home from '../components/client/home';

export default function App() {
  const title = 'Lacteos Premium S.A';
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home></Home>
    </>
  );
}
